id: de.fhir.medication
canonical: http://ig.fhir.de/igs/medication
name: MedicationDE
title: Medication IG DE
status: draft
version: 1.0.0-ballot1
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: 1.0.0
publisher:
  name: HL7 Deutschland
  url: https://hl7.de
pages:
  index.md:
    title: Home
  dosage-index.md:
    title: Einführung
  dosage-concept.md:
    title: Fachliche Rahmenbedingungen
  dosage-differences.md:
    title: Dosis Profile
  dosage-to-text.md:
    title: Textgenerierung
  dosage-to-text-examples.md:
    title: Beispielliste Dosierung
  dosage-examples.md:
    title: Dosage Beispiele
  dosage-constraints.md:
    title: Dosage Constraints
  dosage-to-text-system.md:
    title: Hinzufügen des Dosistextes
  multiple-dosages.md:
    title: Mehrere Dosierungen
  timing-freetext-scheme.md:
    title: Freitext-Dosierung
  timing-mman-scheme.md:
    title: Schema mit Tageszeiten-Bezug
  timing-timeofday-scheme.md:
    title: Schema mit Uhrzeiten-Bezug
  timing-weekday-scheme.md:
    title: Schema mit Wochentags-Bezug
  timing-interval-scheme.md:
    title: Schema für wiederkehrende Intervalle
  timing-comb-interval-scheme.md:
    title: Schema für Kombinationen von Zeitintervallen
  timing-comb-dayofweek-scheme.md:
    title: Schema für Kombinationen von Wochentagen
  duration.md:
    title: Duration
  artifacts.html:
    title: FHIR Summary
  downloads.md:
    title: Downloads
menu:
  Home: index.html
  Dosierungen:
    Einführung: dosage-index.html
    Fachliche Rahmenbedingungen: dosage-concept.html
    Dosis Profile: dosage-differences.html
    Textgenerierung: dosage-to-text.html
    Hinzufügen des Dosistextes: dosage-to-text-system.html
    Beispielliste Dosierung: dosage-to-text-examples.html
    Mehrere Dosierungen: multiple-dosages.html
    Constraints: dosage-constraints.html
  Dosierschemata:
    Freitext-Dosierung: timing-freetext-scheme.html
    Schema mit Tageszeiten-Bezug: timing-mman-scheme.html
    Schema mit Uhrzeiten-Bezug: timing-timeofday-scheme.html
    Schema mit Wochentags-Bezug: timing-weekday-scheme.html
    Schema für wiederkehrende Intervalle: timing-interval-scheme.html
    Schema für Kombinationen von Zeitintervallen: timing-comb-interval-scheme.html
    Schema für Kombinationen von Wochentagen: timing-comb-dayofweek-scheme.html
    Beispiel Dosierungen: dosage-examples.html
  FHIR-Artefakte: artifacts.html
  Downloads: downloads.html
parameters:
  path-pages:
    - input/content
  profile-test-cases:
    - input/testcases/test.json
  no-validate:
    - MedicationRequest/Invalid-C-TimingOnlyOneType-02-of-08
    - MedicationRequest/Invalid-C-TimingOnlyOneType-03-of-08
    - MedicationRequest/Invalid-C-TimingOnlyOneType-04-of-08
    - MedicationRequest/Invalid-C-TimingOnlyOneType-05-of-08
    - MedicationRequest/Invalid-C-TimingOnlyOneType-06-of-08
    - MedicationRequest/Invalid-C-TimingOnlyWhenOrTimeOfDay-01-of-08
    - MedicationRequest/Invalid-Dosage-01-of-12-FreqPeriod-When
    - MedicationRequest/Invalid-Dosage-02-of-12-FreqPeriod-ToD-DayOfWeek
    - MedicationRequest/Invalid-Dosage-03-of-12-FreqPeriod-When-DayOfWeek
    - MedicationRequest/Invalid-Dosage-04-of-12-FreeText-and-structured
    - MedicationRequest/Invalid-Dosage-05-of-12-multiple-types
    - MedicationRequest/Invalid-Dosage-06-of-12-multiple-dosagecodes
    - MedicationRequest/Invalid-Dosage-07-of-12-timing-no-dose
    - MedicationRequest/Invalid-Dosage-09-of-12-C-TimingOnlyOneTimeForInterval
    - MedicationRequest/Invalid-Dosage-10-of-12-When-DiffPeriodU
    - MedicationRequest/Invalid-Dosage-11-of-12-C-TimingOnlyOneWhen
    - MedicationRequest/Invalid-Dosage-12-of-12-C-TimingOnlyOneDayOfWeek
    - MedicationRequest/Invalid-Dosage-C-TimingFrequencyCount-01-of-05
    - MedicationRequest/Invalid-Dosage-C-TimingFrequencyCount-02-of-05
    - MedicationRequest/Invalid-Dosage-C-TimingFrequencyCount-03-of-05
    - MedicationRequest/Invalid-Dosage-C-TimingFrequencyCount-04-of-05
    - MedicationRequest/Invalid-Dosage-C-TimingFrequencyCount-05-of-05
    - MedicationRequest/Invalid-Dosage-C-TimingPeriodUnit-01-of-05
    - MedicationRequest/Invalid-Dosage-C-TimingPeriodUnit-02-of-05
    - MedicationRequest/Invalid-Dosage-C-TimingPeriodUnit-03-of-05
    - MedicationRequest/Invalid-Dosage-C-TimingPeriodUnit-04-of-05
    - MedicationRequest/Invalid-Dosage-C-TimingPeriodUnit-05-of-05
    - MedicationRequest/Invalid-multiple-01-of-10-when
    - MedicationRequest/Invalid-multiple-02-of-10-C-TimingOnlyOneTimeOfDay
    - MedicationRequest/Invalid-multiple-04-of-10-C-TimingOnlyOnePeriodForDayOfWeek
    - MedicationRequest/Invalid-multiple-05-of-10-C-TimingOnlyOnePeriodForDayOfWeek
    - MedicationRequest/Invalid-multiple-06-of-10-C-TimingIntervalOnlyOneFrequency
    - MedicationRequest/Invalid-multiple-07-of-10-C-TimingOnlyOneWhen
    - MedicationRequest/Invalid-multiple-08-of-10-C-TimingOnlyOneTimeOfDay
    - MedicationRequest/Invalid-multiple-09-of-10-C-TimingOnlyOneTimeForInterval
    - MedicationRequest/Invalid-multiple-10-of-10-C-TimingOnlyOneBounds
    - MedicationRequest/Unsupported-Dosage-01-of-20-Count
    - MedicationRequest/Unsupported-Dosage-02-of-20-asNeededBoolean
    - MedicationRequest/Unsupported-Dosage-03-of-20-asNeededCodeableConcept
    - MedicationRequest/Unsupported-Dosage-04-of-20-Method
    - MedicationRequest/Unsupported-Dosage-05-of-20-Route
    - MedicationRequest/Unsupported-Dosage-06-of-20-Site
    - MedicationRequest/Unsupported-Dosage-07-of-20-DoseRange
    - MedicationRequest/Unsupported-Dosage-08-of-20-RateQuantity
    - MedicationRequest/Unsupported-Dosage-09-of-20-RateRange
    - MedicationRequest/Unsupported-Dosage-10-of-20-RateRatio
    - MedicationRequest/Unsupported-Dosage-11-of-20-AdditionalInstruction
    - MedicationRequest/Unsupported-Dosage-12-of-20-MaxDosePerPeriod
    - MedicationRequest/Unsupported-Dosage-13-of-20-MaxDosePerAdministration
    - MedicationRequest/Unsupported-Dosage-14-of-20-MaxDosePerLifetime
    - MedicationRequest/Unsupported-Dosage-15-of-20-Count
    - MedicationRequest/Unsupported-Dosage-16-of-20-CountMax
    - MedicationRequest/Unsupported-Dosage-17-of-20-BoundsPeriod
    - MedicationRequest/Unsupported-Dosage-18-of-20-BoundsRange
    - MedicationRequest/Unsupported-Dosage-19-of-20-Offset
    - MedicationRequest/Unsupported-Dosage-20-of-20-Event
instanceOptions:
  manualSliceOrdering: true
